name: Compilar Tizen Web App

on:
  push:
    branches: [ "main", "master" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      ACTIONS_ALLOW_USE_UNSECURE_NODE_VERSION: true
      FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

    steps:
    - name: Checkout del código
      uses: actions/checkout@v5

    - name: Configurar Java
      uses: actions/setup-java@v5
      with:
        distribution: 'temurin'
        java-version: '11'

    # USANDO LA URL REAL Y DIRECTA DE SAMSUNG TIZEN STUDIO v6.0
    - name: Instalar Tizen CLI
      run: |
        curl -o tizen-cli.bin https://tizen.org
        chmod +x tizen-cli.bin
        ./tizen-cli.bin --accept-license ~/tizen-studio
        echo "~/tizen-studio/tools/ide/bin" >> $GITHUB_PATH

    - name: Configurar Certificado de Firma
      run: |
        echo "${{ secrets.TIZEN_CERTIFICATE_BASE64 }}" | base64 --decode > author.p12
        ~/tizen-studio/tools/ide/bin/tizen security-profiles add -n MiPerfil -a author.p12 -p ${{ secrets.TIZEN_CERTIFICATE_PASSWORD }}

    - name: Compilar App
      run: |
        tizen build-web -- .

    - name: Empaquetar (.wgt)
      run: |
        tizen package -t wgt -s MiPerfil -- ./.buildResult

    - name: Subir archivo .wgt resultante
      uses: actions/upload-artifact@v4
      with:
        name: tizen-widget
        path: ./.buildResult/*.wgt
